### ISSUE TITLE
socket io emit API seems to be wrong

### ISSUE THREAD

**Issue by eastflag** [koush/AndroidAsync#107]
I have a question.
## I used emit API as follows:

```
        JSONArray array = new JSONArray();
        try {
            array.put(new JSONObject().put("type", "public"));
            array.put(new JSONObject().put("name", "aaa"));
            array.put(new JSONObject().put("message", "hi"));
        } catch (JSONException e) {
            e.printStackTrace();
        }
        Log.d("LDK", "array:" + array.toString());
        //This code have bug, I think
        mSocket.emit("message", array);
```

---

But, node.js server prints as follows:
websocket writing 5:::{"name":"message","args":[{"type":"public"}]}
"name", "message" values are not printed.
What happen?

**Comment by nimishbansal** [comment]
Please help me I am also getting erroe in using emit


Here is my code

```
package com.example.nimish.temporaryjava

import android.os.Bundle
import android.support.v7.app.AppCompatActivity
import android.util.Log
import org.json.JSONObject
import org.json.JSONArray
import com.koushikdutta.async.http.AsyncHttpClient
import com.koushikdutta.async.http.socketio.*
import kotlinx.android.synthetic.main.activity_main.*


class MainActivity : AppCompatActivity()
{

    override fun onCreate(savedInstanceState: Bundle?)
    {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        editText.setText("http://192.168.0.101:3000")

        startLocalHost.setOnClickListener {
            SocketIOClient.connect(AsyncHttpClient.getDefaultInstance(), editText.text.toString(), object : ConnectCallback
            {
                override fun onConnectCompleted(ex: Exception?, client: SocketIOClient)
                {
                    if (ex != null)
                    {
                        Log.i("mytag","onConnect server")
                        ex.printStackTrace()
                        return
                    }
                    client.stringCallback = object : StringCallback
                    {
                        override fun onString(string: String?, acknowledge: Acknowledge?)
                        {
                            Log.i("mytag", "onString")
                            println(string)
                        }
                    }

                    client.on("someEvent", object : EventCallback
                    {
                        override fun onEvent(argument: JSONArray, acknowledge: Acknowledge)
                        {
                            Log.i("mytag", "someEvent occured")
                            System.out.println("args: " + argument.toString())
                        }
                    })

                    client.jsonCallback = object : JSONCallback
                    {
                        override fun onJSON(json: JSONObject?, acknowledge: Acknowledge?)
                        {
                            Log.i("mytag", "jsoncallback")
                            println("json: " + json.toString())
                        }

                    }
                }
            })
        }

        receiveLocalHost.setOnClickListener {
            SocketIOClient.connect(AsyncHttpClient.getDefaultInstance(), editText.text.toString(), object : ConnectCallback
            {
                override fun onConnectCompleted(ex: Exception?, client: SocketIOClient)
                {
                    if (ex != null)
                    {
                        Log.i("mytag","onConnect client")
                        ex.printStackTrace()
                        client.emit("someEvent")
                        return
                    }


                }
            })
        }
    }

})
```


and my xml is 
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.nimish.temporaryjava.MainActivity">

    <EditText
        android:id="@+id/editText"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:ems="10"
        android:inputType="textPersonName"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <Button
        android:id="@+id/startLocalHost"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="84dp"
        android:layout_marginTop="44dp"
        android:text="startLocalHost"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.303"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/editText" />

    <Button
        android:id="@+id/receiveLocalHost"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="204dp"
        android:text="receiveLocalHost"
        app:layout_constraintTop_toBottomOf="@+id/startLocalHost"
        tools:layout_editor_absoluteX="113dp" />

    <TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:text="TextView"
        android:textSize="24sp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.501"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/receiveLocalHost"
        app:layout_constraintVertical_bias="0.905" />

</android.support.constraint.ConstraintLayout>

```

What i was simply trying making a local network chatting app ,without using internet at all.
So what I did was when startLocalHost button was clicked.I take the text from editText and use it to create a web socket as you mentioned in the documentation and I tapped this startLocalHostbutton on my first phone(with ip http://192.168.0.101).
Also I run the same app on my other phone(192.168.0.100) and entered the same ip in edit text and tab button receiveLocalHost where I connected to the web socket created by (192.168.0.101) and also tried to emit an event by using client.emit (but it created error with error log :(



> 03-18 17:02:18.517 4827-6184/com.example.nimish.temporaryjava E/AndroidRuntime: FATAL EXCEPTION: AsyncServer
>                                                                                 Process: com.example.nimish.temporaryjava, PID: 4827
>                                                                                 java.lang.NullPointerException: Attempt to invoke interface method 'void com.koushikdutta.async.http.socketio.transport.SocketIOTransport.send(java.lang.String)' on a null object reference
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOConnection.emitRaw(SocketIOConnection.java:58)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOClient.emitRaw(SocketIOClient.java:19)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOClient.emit(SocketIOClient.java:46)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOClient.emit(SocketIOClient.java:27)
>                                                                                     at com.example.nimish.temporaryjava.MainActivity$onCreate$2$1.onConnectCompleted(MainActivity.kt:73)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOClient$1.onConnectCompleted(SocketIOClient.java:82)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOConnection$5.onSelect(SocketIOConnection.java:263)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOConnection.select(SocketIOConnection.java:199)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOConnection.reportDisconnect(SocketIOConnection.java:250)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOConnection.access$000(SocketIOConnection.java:30)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOConnection$1.onCompleted(SocketIOConnection.java:161)
>                                                                                     at com.koushikdutta.async.http.socketio.SocketIOConnection$1.onCompleted(SocketIOConnection.java:157)
>                                                                                     at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
>                                                                                     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
>                                                                                     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:124)
>                                                                                     at com.koushikdutta.async.future.TransformFuture.error(TransformFuture.java:22)
>                                                                                     at com.koushikdutta.async.future.TransformFuture.onCompleted(TransformFuture.java:9)
>                                                                                     at com.koushikdutta.async.future.SimpleFuture.handleCallbackUnlocked(SimpleFuture.java:107)
>                                                                                     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:141)
>                                                                                     at com.koushikdutta.async.future.SimpleFuture.setComplete(SimpleFuture.java:124)
>                                                                                     at com.koushikdutta.async.http.AsyncHttpClient.invokeWithAffinity(AsyncHttpClient.java:521)
>                                                                                     at com.koushikdutta.async.http.AsyncHttpClient.access$800(AsyncHttpClient.java:51)
>                                                                                     at com.koushikdutta.async.http.AsyncHttpClient$7.run(AsyncHttpClient.java:534)
>                                                                                     at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740)
>                                                                                     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758)
>                                                                                     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
>                                                                                     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
>                                                                                     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
> 

Can you help me out :-)
