### ISSUE TITLE
onDataAvailable

### ISSUE THREAD

**Issue by RedAndBlack** [koush/AndroidAsync#148]
Hello!
I use AsyncServer.connectSocket to send and receive data between my app and tcp server.
When tcp-server sends about 100 bytes, everything seems ok, but when it sends about 2000 bytes bufferList has only first byte.
How should I read all data?
code:
socket.setDataCallback(new DataCallback() {

```
                        @Override
                        public void onDataAvailable(DataEmitter dataemmiter, ByteBufferList bufferList) {

                            Log.v(TAG, String.format("onDataAvailable bufferList = %s", bufferList.peekString()));
                        }
                    });
```

**Comment by MatanTubul** [comment]
Do you have an example for `watch for subsequent calls`?
