### ISSUE TITLE
Connection being closed in websockets just after being connected

### ISSUE THREAD

**Issue by omerjerk** [koush/AndroidAsync#212]
I'm creating a websocket server on one device and a websocket client on another device.
The client is connecting to the web socket server easily but just after sending and receiving some strings, the connection is closed. I'm using the example code given in the README file.

How should I maintain a long lasting connections using websockets ?

**Comment by Kartik-RTP** [comment]
@omerjerk  : Hey , can u please tell the solution . your one line comment is not helping  me solve the problem at my end?
