### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: No peer certificate

### ISSUE THREAD

**Issue by castrojr913** [koush/AndroidAsync#284]
When I try to upload an image to a secure server, through a post request, it generates an exception associated to SSL chain: javax.net.ssl.SSLPeerUnverifiedException No peer certificate. Then, the error provokes the next exception: java.lang.NullPointerException: Attempt to invoke interface method ‘void 
com.koushikdutta.async.callback.CompletedCallback.onCompleted(java.lang.Exception)' on a null object reference.

I use OpenSSL to check connection with the server and and it works.

``openssl s_client -connect myserver.com:443``

``
Certificate chain
 0 s:/OU=Domain Control Validated/OU=nsProtect Secure Xpress/CN=myserver.com
   i:/C=US/O=Network Solutions L.L.C./CN=Network Solutions DV Server CA
 1 s:/C=US/O=Network Solutions L.L.C./CN=Network Solutions DV Server CA
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
``

For a Non-secure server, it works perfectly.

**Comment by castrojr913** [comment]
CONNECTED(00000003)
depth=2 /C=US/O=Network Solutions L.L.C./CN=Network Solutions Certificate Authority
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/serialNumber=830353592/1.3.6.1.4.1.311.60.2.1.3=US/1.3.6.1.4.1.311.60.2.1.2=Florida/1.3.6.1.4.1.311.60.2.1.1=Jacksonville/businessCategory=Private Organization/C=US/postalCode=32256/ST=FL/L=Jacksonville/street=5210 Belfort Road, suite 320/O=CE Broker, Inc./OU=IT/OU=Secure Link EV SSL/CN=www.cebroker.com
   i:/C=US/ST=VA/L=Herndon/O=Network Solutions L.L.C./CN=Network Solutions EV Server CA 2
 1 s:/C=US/ST=VA/L=Herndon/O=Network Solutions L.L.C./CN=Network Solutions EV Server CA 2
   i:/C=US/O=Network Solutions L.L.C./CN=Network Solutions Certificate Authority
 2 s:/C=US/O=Network Solutions L.L.C./CN=Network Solutions Certificate Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGNDCCBRygAwIBAgIQFhWs7wuEVn6+ADnKEOlZgTANBgkqhkiG9w0BAQsFADB6
MQswCQYDVQQGEwJVUzELMAkGA1UECBMCVkExEDAOBgNVBAcTB0hlcm5kb24xITAf
BgNVBAoTGE5ldHdvcmsgU29sdXRpb25zIEwuTC5DLjEpMCcGA1UEAxMgTmV0d29y
ayBTb2x1dGlvbnMgRVYgU2VydmVyIENBIDIwHhcNMTQxMTExMDAwMDAwWhcNMTYx
MTEwMjM1OTU5WjCCAUgxEjAQBgNVBAUTCTgzMDM1MzU5MjETMBEGCysGAQQBgjc8
AgEDEwJVUzEYMBYGCysGAQQBgjc8AgECEwdGbG9yaWRhMR0wGwYLKwYBBAGCNzwC
AQETDEphY2tzb252aWxsZTEdMBsGA1UEDxMUUHJpdmF0ZSBPcmdhbml6YXRpb24x
CzAJBgNVBAYTAlVTMQ4wDAYDVQQREwUzMjI1NjELMAkGA1UECBMCRkwxFTATBgNV
BAcTDEphY2tzb252aWxsZTElMCMGA1UECRMcNTIxMCBCZWxmb3J0IFJvYWQsIHN1
aXRlIDMyMDEYMBYGA1UEChMPQ0UgQnJva2VyLCBJbmMuMQswCQYDVQQLEwJJVDEb
MBkGA1UECxMSU2VjdXJlIExpbmsgRVYgU1NMMRkwFwYDVQQDExB3d3cuY2Vicm9r
ZXIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1sNBLuFahaqF
HPT1UbOoM+EE7dxMu30ZVXEEvcS3yIlJ4tXa+J++kIEmQ1JwSEVcUUEB9HR8VLtu
ZoSOqKsDn9xe9u+iXdzpiH40pzttF1IUEPEuZNMxurS4IKQ/9/Qu/Q0jpGBi+mTi
wMfdjwAZfzJhTcvgRjRQ3h/eqoua7J70dZFNRWrzT9aPJnVeVRuf0N+f6Y+xC1Bq
sX0a4NO0mquFUR96YuCjecYutk3Bn04nyztskYopcnhwY/65d8EAQbd9ZJbhox66
ZGe0R5uQMsBJRCuBRCm1a3OEKWVvI6/lghJSTc5OS2WCOQv+uqnnLetHJPILq6Ri
KVbNnhBnwQIDAQABo4IB5DCCAeAwHwYDVR0jBBgwFoAUjzdKhJz0jsdmlpC0ro+6
XqIWqsQwHQYDVR0OBBYEFNJcyQyEYyefFIFYgHqJyBceFoxwMA4GA1UdDwEB/wQE
AwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
AjBuBgNVHSAEZzBlMGMGDCsGAQQBhg4BAgEIATBTMFEGCCsGAQUFBwIBFkVodHRw
Oi8vd3d3Lm5ldHdvcmtzb2x1dGlvbnMuY29tL2xlZ2FsL1NTTC1sZWdhbC1yZXBv
c2l0b3J5LWV2LWNwcy5qc3AwSQYDVR0fBEIwQDA+oDygOoY4aHR0cDovL2NybC5u
ZXRzb2xzc2wuY29tL05ldHdvcmtTb2x1dGlvbnNFVlNlcnZlckNBMi5jcmwwewYI
KwYBBQUHAQEEbzBtMEQGCCsGAQUFBzAChjhodHRwOi8vY3J0Lm5ldHNvbHNzbC5j
b20vTmV0d29ya1NvbHV0aW9uc0VWU2VydmVyQ0EyLmNydDAlBggrBgEFBQcwAYYZ
aHR0cDovL29jc3AubmV0c29sc3NsLmNvbTApBgNVHREEIjAgghB3d3cuY2Vicm9r
ZXIuY29tggxjZWJyb2tlci5jb20wDQYJKoZIhvcNAQELBQADggEBAEDLUw/QPhV1
VD93upXpIJsBWQme5c0BcqBUe/juB9E2nH0fDp2Gf6Wj7Wh4asQrIq6nJ1/99jQa
7qAa1+FXi+ihLKpJVXLP+jLFvlyYDC7HOn2rS+F2qWhpcD34aYrqpWfOytnElBJz
ttRdIQCqQCuzc/f2u6myThBhcLYe/DBt+ytkWAHRLqe3xVLIIX+Vuwp26636GqPd
UyD7Cz4Vrj38340AHXon0EEZziAwPKC1Fv9HiABq0xA/KXki/jPXWLp0OKo1XN2I
rhzURXyBDgkAgwT9MI9v1GVRRIm6CFVf5CddcVksNriAl6o72u3XSByY2Qpf337Y
M03RGFsEAqM=
-----END CERTIFICATE-----
subject=/serialNumber=830353592/1.3.6.1.4.1.311.60.2.1.3=US/1.3.6.1.4.1.311.60.2.1.2=Florida/1.3.6.1.4.1.311.60.2.1.1=Jacksonville/businessCategory=Private Organization/C=US/postalCode=32256/ST=FL/L=Jacksonville/street=5210 Belfort Road, suite 320/O=CE Broker, Inc./OU=IT/OU=Secure Link EV SSL/CN=www.cebroker.com
issuer=/C=US/ST=VA/L=Herndon/O=Network Solutions L.L.C./CN=Network Solutions EV Server CA 2
---
No client certificate CA names sent
---
SSL handshake has read 4419 bytes and written 456 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES128-SHA
    Session-ID: DA45000036E22BA6F56377B28B0613188971BB982683479045085A0F38549B40
    Session-ID-ctx: 
    Master-Key: E75B905F05C2CFF81387F10359F62A6670ED3D63EBFEA198F7203DF511DF75C77AE7C8A5E4CF9533E3AE924603B56AF4
    Key-Arg   : None
    Start Time: 1426512119
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

**Comment by koush** [comment]
Can you give me the stack trace on the null pointer you reported?

**Comment by castrojr913** [comment]
This issue is very old, but I haven't been able to re-create this trouble so far because of I'm not working in the company where I could throw this exception. If I see that this issue shows up again, I will reopen it again. Either way, thank your for the help :).
