### ISSUE TITLE
Response DataCallback Never Called

### ISSUE THREAD

**Issue by eygraber** [koush/AndroidAsync#287]
I'm trying to use AndroidAsync as the client for Retrofit, and I've run into some issues with getting response data using v. 2.0.1.

I call:

```
// client = AsyncClien
AsyncHttpResponse response = client.execute(request, new HttpConnectCallback() {
    @Override
    public void onConnnectCompleted(Exception e, AsyncHttpResponse asyncHttpResponse) {
        // ignore since we get response synchronously
    }
}).get();
```

I then use an `InputStreamParser` (from `ION`) to get an `InputStream` that can be used for the retrofit response:

```
return new InputStreamParser().parse(response).get();
```

However, since updating to 2.0.1 that call hangs forever. I tried setting a `DataCallback` on the response, and it never got called:

```
response.setDataCallback(new DataCallback() {
    @Override
    public void onDataAvailable(DataEmitter emitter, ByteBufferList bb) {
            Log.i(TAG, "In onDataAvailable");
    }
});
```

I've used the debugger to step through the code, and those lines are getting hit. The parser never returns, and the callback never gets called. Any idea what could be causing this?

**Comment by koush** [comment]
@eygraber can you put together a quick method that demonstrates this against a live url?

**Comment by eygraber** [comment]
@koush sent you a link

**Comment by eygraber** [comment]
@koush just for reference, it looks like Retrofit is phasing out the ability to use custom clients.
