### ISSUE TITLE
Client example for https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-websocket-tomcat

### ISSUE THREAD

**Issue by alfredorueda** [koush/AndroidAsync#304]
Thank you very much for this excellent open source project . It is super helpful to many software developers.

Is it possible to connect an application developed with AndroidAsync to Spring Application like:
https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-websocket-tomcat ??

A simple example would be extremely useful for the Spring developer community.

Thank you for your help and support!

**Comment by pkletsko** [comment]
Hi,

I also interested in this example .

**Comment by koush** [comment]
Not familiar with Spring. If it's just a http webservice or websocket service, yes, it is possible.

It likely uses a custom websocket protocol, but I will not be implementing it.
