### ISSUE TITLE
Websocket Send from InputStream

### ISSUE THREAD

**Issue by nativecss** [koush/AndroidAsync#312]
I'm trying to use this method to send Websocket data. 
    send(byte [] bytes, int offset, int len);

I would like to send from a stream in order to cut down memory use. 
I've tried to send a message like this:

    String register = "{\"message\":\"register\"}";
    byte[] myBytes = register.getBytes();
    webSocket.send(myBytes,0,myBytes.length);

This message isn't sent. do I need to send EOF or somehow flush the data. 

Is it implemented? I'm happy to implement this for you if you can provide some pointers.

**Comment by paulpdaniels** [comment]
It is definitely implemented.  You shouldn't need to do anything special to send the data.  Are you able to send data in the opposite direction successfully?

**Comment by nativecss** [comment]
Found the problem. It was sending it as binary data not a string, which was being ignored by my webservice.

Thanks
