### ISSUE TITLE
No method to disconnect the websocket

### ISSUE THREAD

**Issue by bweng2000** [koush/AndroidAsync#332]
My Android app program is connecting to a websocket server using AndroidAsync. The web server  is continuously pushing continuous data stream to my Android client. Upon a certain counter number, I want to disconnect the websocket from Android. But I didn't find a method to call to disconnect the websocket. My websocket client looks like

```java
webSocket.setStringCallback(new WebSocket.StringCallback() {

                    @Override
                    public void onStringAvailable(final String s) {
                        if(counter >= NUM_JSON_SEG) {
                            // How do I disconnect websocket connection here?
                            Intent intent = new Intent(mContext, AnotherActivity.class);
                            intent.putExtra("Code", code);
                            startActivity(intent);
                        }
``` 

As you can see, when the condition is met (`counter >= NUM_JSON_SEG`), I want to disconnect the websocket and start the new activity. But I didn't find a method in AndroidAsync to do this inside the `onStringAvailable` callback. Is this feature missing in AndroidAsync? If I don't disconnect the websocket, even if the new activity is launched, the underlying websocket is still open and the callback is still receiving data from the server.

**Comment by urmilparikh** [comment]
You can use webSocket.close()

**Comment by bweng2000** [comment]
@urmilparikh Thanks a lot. That works well.
