### ISSUE TITLE
How to capture 404

### ISSUE THREAD

**Issue by dickensas** [koush/AndroidAsync#355]
05-27 17:38:51.938: I/System.out(4231): emitter: HTTP/1.1 404 Not Found
05-27 17:38:51.938: I/System.out(4231): Server: nginx/1.4.5
05-27 17:38:51.938: I/System.out(4231): Date: Wed, 27 May 2015 12:07:48 GMT
05-27 17:38:51.938: I/System.out(4231): Content-Type: text/html;charset=ISO-8859-1
05-27 17:38:51.938: I/System.out(4231): Content-Length: 1378
05-27 17:38:51.938: I/System.out(4231): Connection: keep-alive
05-27 17:38:51.938: I/System.out(4231): Set-Cookie: JSESSIONID=s3mkh8m57gj51onqr5n7xcj40;Path=/
05-27 17:38:51.938: I/System.out(4231): Cache-Control: must-revalidate,no-cache,no-store

but there is no callback method for this

**Comment by koush** [comment]
AsyncHttpResponse has a code() method on it.

**Comment by koush** [comment]
Or are you using websockets?

**Comment by dickensas** [comment]
yes, I am using websockets
Future<WebSocket> client = AsyncHttpClient.getDefaultInstance().websocket("ws://localhost:7070/ws/server", "xmpp", wsConnListn);
