### ISSUE TITLE
websocket client closed socket after connection, while chrome console keeps, why

### ISSUE THREAD

**Issue by feabauer** [koush/AndroidAsync#357]
Hi koush, thank u for your great work!

I copied your sample code for websocket in webpage, one for server, and one for client.

When I connect server with console of Chrome browser with javascript, it works well. (client sockets keep in _sockets, and NO onComplete set by  webSocket.setClosedCallback is called). When I close the websocket with "close()", then the onComplete will be called in server side.

While with android client, just after websocket connects and message sent, the onComplete will be received/called soon, and the client socket will be removed from _sockets. The socket looks like closed. But when I use socket to send message, still works, so the connection is living. It makes me confused. 

//**********************************************
Code is listed as following:

server
=====================
server.websocket("/live", new WebSocketRequestCallback() {
            @Override
            public void onConnected(final WebSocket webSocket, AsyncHttpServerRequest request) {

                _sockets.add(webSocket);

                //Use this to clean up any references to your websocket
                webSocket.setClosedCallback(new CompletedCallback() {
                    @Override
                    public void onCompleted(Exception ex) {
                        try {
                            if (ex != null)
                                Log.e("WebSocket", "Error");
                        } finally {
                            _sockets.remove(webSocket);
                        }
                    }
                });

                webSocket.setStringCallback(new WebSocket.StringCallback() {
                    @Override
                    public void onStringAvailable(String s) {
                        if ("Hello Server".equals(s))
                            webSocket.send("Welcome Client!");
                    }
                });

                webSocket.send("connected.");
            }
        });

and android client: (within onCreate of the main activity)
===================
        AsyncHttpClient.getDefaultInstance().websocket(hostAddress, null, new AsyncHttpClient.WebSocketConnectCallback() {
            @Override
            public void onCompleted(Exception ex, WebSocket webSocket) {
                if (ex != null) {
                    ex.printStackTrace();
                    return;
                }

                mSocket = webSocket;

                mSocket.setStringCallback(new WebSocket.StringCallback() {
                    public void onStringAvailable(String s) {
                        System.out.println("I got a string: " + s);
                    }
                });

                mSocket.send("Hello Server");
            }
        });

chrome console:
====================
sk = new WebSocket('ws://192.168.43.1:3000/live'); 
sk.onopen = function(e){console.log(e);}; 
sk.onmessage = function(e){console.log(e);}
....
sk.send("Hello Server")   // no call onComplete
....
sk.close()  //server side calls onComplete here
....
===============================================
I check "_sockets" array in server side, each connection keeps well in "_sockets" array with chrome console, while android client, each connection will be closed/removed in server side "webSocket.setClosedCallback", soon after message send/received.

I don't understand why the websocket will be closed by itself.

 Look for your help.

Thanks.

**Comment by feabauer** [comment]
Soon after  websocket in android client connects the server , server side will receive/call "webSocket.setClosedCallback". Can I say the client has closed the connection?

But what lets me confused is: the websocket in android client can still send messages to server, so the socket is living. What is the time of  "closed callback" of "websocket"?

For comparison, with chrome console/client, after successful connection, or open, or message, no "webSocket.setClosedCallback" will be called in server side. So I believe the websocket connection remains.

**Comment by Kartik-RTP** [comment]
Hey! whats the solution ?? How to keep the connection alive?
