### ISSUE TITLE
Did AndroidAsync support HTTP DELETE method?

### ISSUE THREAD

**Issue by jasonchuang** [koush/AndroidAsync#380]
Under the koushikdutta/async/http folder, I only found AsyncHttpGet, AsyncHttpPut and AsyncHttpPost classes. How can I send http delete request without the help of AsyncHttpDelete?
Thanks.

**Comment by rockwotj** [comment]
You can send it by specifying the method in a AsyncHttpRequest object

```java
String url = "http://foobar.com/api";
String method = "DELETE";
new AsyncHttpRequest(url, method);
```
