### ISSUE TITLE
All ws connections return 200 instead 101 but wss works

### ISSUE THREAD

**Issue by adelburekovic** [koush/AndroidAsync#381]
This is the code i used for connection:

<pre>
<code>
 AsyncHttpClient.getDefaultInstance().websocket("ws://echo.websocket.org", null, new AsyncHttpClient.WebSocketConnectCallback() {
            @Override
            public void onCompleted(Exception ex, com.koushikdutta.async.http.WebSocket webSocket) {

                if (ex != null) {
                    ex.printStackTrace();
                    return;
                }

                webSocket.setStringCallback(new com.koushikdutta.async.http.WebSocket.StringCallback() {
                    public void onStringAvailable(String s) {
                        System.out.println("I got a string: " + s);

                    }
                });

                webSocket.setClosedCallback(new CompletedCallback() {
                    @Override
                    public void onCompleted(Exception ex) {

                    }
                });

            }
        });
</code>
</pre>

Response i get back is:

<pre>
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Length: 697
Content-Type: application/vnd.wap.xhtml+xml
Date: Tue, 18 Aug 2015 23:49:12 GMT
</pre>

Any tips would be appreciated.  Thing is  that wss://echo.websocket.org for example works perfectly.

**Comment by rkeiii** [comment]
I'm seeing the same issue. Some additional details...

I have three development devices, a Nexus 5 (KitKat), an LG G3 (LoliPop) and an ASUS Tablet (KitKat).

Only the LG G3 on Lolipop experiences this issue.

I've included a packet capture snippet image below noting the differences between the request generated by AndroidAsync under KitKat versus under Lolipop.

I have not attempted using wss:// so I cannot confirm or deny if that protocol shows the same issue.
![websocket_diff_cut](https://cloud.githubusercontent.com/assets/753217/9569193/df8a7248-4f18-11e5-8611-e701c4327d4d.png)

**Comment by koush** [comment]
This isn't a library issue, it's a server issue. Your server, or the route to the server, is doing something incorrect. My guess, since wss works, is that there's a broken proxy somewhere in between. wss works because proxies just act as blind pass throughs for tls content.

**Comment by rkeiii** [comment]
Thanks for taking the time to reply koush.

While I'm admittedly a novice android developer I think there is direct evidence of a client/library issue here.

Under Android 5.x Lolipop the AndroidAsync library fails to create the "Upgrade" and "Connection" headers in the initial request to the server. It seems to me it's impossible for this to be strictly a server issue since the initial request is what's incorrectly formatted.

I tried adding a custom middleware to force the "Upgrade" and "Connection" headers and still they were missing from the request.

Please see the screenshot I attached to my last post. I can provide my code as well if it would help (but I pretty much copied and pasted from your web socket test class).

**Comment by koush** [comment]
@rkeiii Please turn on verbose logging on the websocket request and get me those logs. That will show what the device is sending _before_ it goes through any proxies.

A proxy can easily remove various request headers. And I believe that is the case here.

**Comment by koush** [comment]
An easy way to turn on verbose logging for hte websocket request is by using httpClient.setLogging(LOG.Verbose...)

**Comment by koush** [comment]
For reference, here's where the headers are added:
https://github.com/koush/AndroidAsync/blob/master/AndroidAsync/src/com/koushikdutta/async/http/WebSocketImpl.java#L145

You can see they are all added in one place. The fact that some headers remain, and the "Connection" header (which is often modified by proxies for caching/chunking purposes) was removed is an indication of a bad middle man.

**Comment by koush** [comment]
My guess is that one device is on wifi (or a different carrier) than the other. The Android OS version is a red herring.

**Comment by rkeiii** [comment]
@koush 

You are correct. The client correctly sets the headers and the Android version was indeed a red herring.

```
08-30 18:52:02.949  13079-13376/life.stall V/Request Info﹕ (40 ms) http://api.my.host/messages/byStall/55de8d3d3b7ce90001000027: socket connected
08-30 18:52:02.954  13079-13376/life.stall V/Request Info﹕ (45 ms) http://api.my.host/messages/byStall/55de8d3d3b7ce90001000027:
    GET /messages/byStall/55de8d3d3b7ce90001000027 HTTP/1.1
    Host: api.my.host
    User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.0.1; VS985 4G Build/LRX21Y)
    Accept-Encoding: gzip, deflate
    Connection: Upgrade
    Accept: */*
    Sec-WebSocket-Version: 13
    Sec-WebSocket-Key: yYjMC+o1TUaQrfIIAS9KFg==
    Sec-WebSocket-Extensions: x-webkit-deflate-frame
    Upgrade: websocket
    Sec-WebSocket-Protocol: websocket
    Pragma: no-cache
    Cache-Control: no-cache
    X-Stall-Api-Key: XXXXXXXXXXXXXXXXXXXXXXXXX
    X-Stall-UserID: XXXXXXXXXXXXXXXXXXXXXXXXX
    X-Stall-Token: XXXXXXXXXXXXXXXXXXXXXXXXX
    X-Stall-Device-UUID: XXXXXXXXXXXXXXXXXXXXXXXXX
08-30 18:52:02.959  13079-13376/life.stall V/Request Info﹕ (50 ms) http://api.my.host/messages/byStall/55de8d3d3b7ce90001000027: request completed
08-30 18:52:03.011  13079-13079/life.stall D/BubblePopupHelper﹕ isShowingBubblePopup : false
08-30 18:52:03.011  13079-13079/life.stall D/BubblePopupHelper﹕ isShowingBubblePopup : false
08-30 18:52:03.057  13079-13079/life.stall D/CliptrayUtils﹕ setInputTypeforClipTray(): 0
08-30 18:52:03.080  13079-13376/life.stall V/Request Info﹕ (171 ms) http://api.my.host/messages/byStall/55de8d3d3b7ce90001000027: Received headers:
    HTTP/1.1 200 OK
    Content-Type: application/json
    Content-Length: 1699
    X-Content-Type-Options: nosniff
    Server: thin
    Via: HTTP/1.1 localhost:2020 (Brazil/2.0)
    Date: Mon, 31 Aug 2015 01:52:03 GMT
    Connection: Keep-Alive
08-30 18:52:03.082  13079-13376/life.stall V/Request Info﹕ (173 ms) http://api.my.host/messages/byStall/55de8d3d3b7ce90001000027: Final (post cache response) headers:
    HTTP/1.1 200 OK
    Content-Type: application/json
    Content-Length: 1699
    X-Content-Type-Options: nosniff
    Server: thin
    Via: HTTP/1.1 localhost:2020 (Brazil/2.0)
    Date: Mon, 31 Aug 2015 01:52:03 GMT
    Connection: Keep-Alive
08-30 18:52:03.082  13079-13376/life.stall D/Request Info﹕ (173 ms) http://api.my.host/messages/byStall/55de8d3d3b7ce90001000027: Connection successful
08-30 18:52:03.085  13079-13376/life.stall E/Request Info﹕ (176 ms) http://api.my.host/messages/byStall/55de8d3d3b7ce90001000027: exception during response
08-30 18:52:03.092  13079-13376/life.stall E/Request Info﹕ Attempt to invoke interface method 'void com.koushikdutta.async.http.WebSocket.setStringCallback(com.koushikdutta.async.http.WebSocket$StringCallback)' on a null object reference
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.koushikdutta.async.http.WebSocket.setStringCallback(com.koushikdutta.async.http.WebSocket$StringCallback)' on a null object reference
            at life.stall.view.StallBox$2.onCompleted(StallBox.java:98)
            at com.koushikdutta.async.http.AsyncHttpClient$11.onConnectCompleted(AsyncHttpClient.java:699)
            at com.koushikdutta.async.http.AsyncHttpClient.reportConnectedCompleted(AsyncHttpClient.java:169)
            at com.koushikdutta.async.http.AsyncHttpClient.access$200(AsyncHttpClient.java:50)
            at com.koushikdutta.async.http.AsyncHttpClient$4.setDataEmitter(AsyncHttpClient.java:392)
            at com.koushikdutta.async.http.AsyncHttpResponseImpl.emitter(AsyncHttpResponseImpl.java:73)
            at com.koushikdutta.async.http.HttpTransportMiddleware$1.onStringAvailable(HttpTransportMiddleware.java:86)
            at com.koushikdutta.async.LineEmitter.onDataAvailable(LineEmitter.java:27)
            at com.koushikdutta.async.Util.emitAllData(Util.java:23)
            at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:146)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:788)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
08-30 18:52:03.094  13079-13376/life.stall V/Request Info﹕ (185 ms) http://api.my.host/messages/byStall/55de8d3d3b7ce90001000027: closing out socket (exception)
```

My code...

```
   private void refreshMessages() {
        final LinearLayout layout = (LinearLayout) findViewById(R.id.stallMessages);
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT);
        findViewById(R.id.loadingPanel).setVisibility(View.VISIBLE);

        final StallApplication app = (StallApplication) getApplicationContext();

        final Semaphore semaphore = new Semaphore(0);

        AsyncHttpClient client = AsyncHttpClient.getDefaultInstance();
        client.insertMiddleware(new StallAuthMiddleware(StallApplication.apiKey,
                                                        app.getCurUserId(),
                                                        app.getCurToken(),
                                                        app.deviceUDID()));
        client.insertMiddleware(new ForceWebsocketMiddleware());
        String currentStall = app.getCurStall().getId();

        client.websocket("ws://api.my.host/messages/byStall/" + currentStall, "websocket", new AsyncHttpClient.WebSocketConnectCallback() {
            @Override
            public void onCompleted(Exception ex, final WebSocket webSocket) {
                webSocket.setStringCallback(new WebSocket.StringCallback() {
                    @Override
                    public void onStringAvailable(final String s) {
                        runOnUiThread(new Thread() {
                            @Override
                            public void run() {
```

I still don't get where that NPE is coming from but I do see that the library is doing it's job correctly. I also have no clue what's ripping those headers out of the request.

I run a mobile hotspot on my LG VS985 5.0.x device that my kitkat devices use to connect to the internet. So again you are correct that one device is on wifi while the other talks directly to Verizon (but they both end up going out the same internet connection so I'm still confused).

In any event you were correct in closing this.

**Comment by koush** [comment]
NPE is happening because no websocket was returned due to connect failure, and you are attempting to call setStringCallback on a null object.

**Comment by koush** [comment]
Your mobile hotspot is acting as a transparent proxy.

**Comment by rkeiii** [comment]
Yep that makes perfect sense. Thanks again for the your help.

**Comment by rkeiii** [comment]
For anyone else who might be experiencing something like this...

The root cause for me was running AdBlock Plus on my phone. It was proxying the requests and ripping out the headers.

**Comment by koush** [comment]
lol...
