### ISSUE TITLE
Stale DNS

### ISSUE THREAD

**Issue by dejami-MBrothers** [koush/AndroidAsync#388]
I'm getting a periodic UnknownHostException loading images through Ion. The problem is most common on s3.amazonaws.com. After a lot of digging it seems they change their IP addresses a lot. It looks like AndroidAsync handles it's own DNS caching, so my questions are:

1) Does your DNS cahce respect TTL?
2) Is there a way to programatically flush your DNS cache if I get an UnknownHostException?

**Comment by koush** [comment]
Nothing special happening with DNS. Using standard Android DNS lookup. No caching.

https://github.com/koush/AndroidAsync/blob/master/AndroidAsync/src/com/koushikdutta/async/AsyncServer.java#L419

**Comment by FreakTheMighty** [comment]
@dejami-MBrothers did you every find a resolution to your problem? I believe I'm seeing a similar issue. I mentioned periodic `UnkownHostException`s over here https://github.com/koush/ion/issues/345#issuecomment-152357555.

**Comment by dejami-MBrothers** [comment]
@FreakTheMighty Not really. I did figure out that I was getting this issue exclusively with redirect URLs or images served up by an API. Facebook profile pics are broken more often that not.
