### ISSUE TITLE
Special port zero! How to get the real port assigned automatically by OS?

### ISSUE THREAD

**Issue by ferchang** [koush/AndroidAsync#419]
We can set special port 0 for AsyncServer/AsyncHttpServer, and that way a free port number is automatically assigned by OS, but seems there is no way to tell that port number from your library.

**Comment by mmimeault** [comment]
YEs,
when you call AsyncHttpServer.listen(0)
it returns a AsyncServerSocket.
You can then call getLocalPort on it.

**Comment by koush** [comment]
yup
