### ISSUE TITLE
Cancelling a SimpleFuture given by connectSocket() will not call onConnectCompleted() callback

### ISSUE THREAD

**Issue by delitestudio** [koush/AndroidAsync#483]
We are doing this simple action:

`cancellableSocket = AsyncServer.getDefault().connectSocket(getAddress(), this);`

Then we are cancelling it with (after an amount of time):

`cancellableSocket.cancel();`

But `onConnectCompleted` will never be called.

**Comment by koush** [comment]
Correct. It was cancelled.

**Comment by delitestudio** [comment]
Ok, so it was the correct behaviour. We're trying to implement a timeout for the `connectSocket` and we have used a timer that will cancel connection so we thought it was simpler if the cancel action would call automatically the `onConnectCompleted` with an `TimeoutException` in it.

But now that we are sure that a cancelled `SimpleFuture` must not call a completion handler because, of sure, it was cancelled, what is the best way to implement a timeout for the `AsyncServer.getDefault().connectSocket(getAddress(), this)`?

**Comment by koush** [comment]
AsyncServer.getDefault().postDelayed(new Runnable
 run{
   // call cancel
   
 }
}, timeout)

**Comment by delitestudio** [comment]
Is this correct?

```
cancellableSocket = AsyncServer.getDefault().connectSocket(getAddress(), this);
AsyncServer.getDefault().postDelayed(new Runnable() {
	@Override
	public void run() {
		if (cancellableSocket.cancel())
			onConnectCompleted(new Exception("Timeout!"), null);
	}
}, 5000);
```

If yes, how we can stop the timeout? For example if user aborts connection before timeout has been elapsed.

**Comment by delitestudio** [comment]
I think we have discovered how to do it in a correctly way:

```
if (scheduled != null) {
	AsyncServer.getDefault().removeAllCallbacks(scheduled);
}
```

Where:

```
cancellableSocket = AsyncServer.getDefault().connectSocket(getAddress(), this);
scheduled = AsyncServer.getDefault().postDelayed(new Runnable() {
    @Override
    public void run() {
        if (cancellableSocket.cancel())
            onConnectCompleted(new Exception("Timeout!"), null);
    }
}, 5000);
```

**Comment by koush** [comment]
Yes, that is correct.
