### ISSUE TITLE
Invalid deflated data

### ISSUE THREAD

**Issue by nukix** [koush/AndroidAsync#491]
I send a json string to server.  And I use '{"type":"1234"}' string.  It was success to get the same string when I  was the first send from server.  But I send the same string to server, I got a IOException. 

java.io.IOException: Invalid deflated data
at com.koushikdutta.async.http.HybiParser.emitFrame(HybiParser.java:407)
at com.koushikdutta.async.http.HybiParser.access$800(HybiParser.java:46)
at com.koushikdutta.async.http.HybiParser$5.onDataAvailable(HybiParser.java:203)
at com.koushikdutta.async.DataEmitterReader.handlePendingData(DataEmitterReader.java:24)
at com.koushikdutta.async.DataEmitterReader.onDataAvailable(DataEmitterReader.java:41)
at com.koushikdutta.async.Util.emitAllData(Util.java:23)
at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)

What is wrong? I use the newest version 2.1.6.

**Comment by nukix** [comment]
I use github AndroidAsync library, it's not wrong. And I use `compile 'com.android.support:appcompat-v7:24.2.1'`, it's wrong.

**Comment by Kartik-RTP** [comment]
i am getting the same error
`04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err: java.io.IOException: Invalid deflated data
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.http.HybiParser.emitFrame(HybiParser.java:407)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.http.HybiParser.access$800(HybiParser.java:46)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.http.HybiParser$5.onDataAvailable(HybiParser.java:203)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.DataEmitterReader.handlePendingData(DataEmitterReader.java:24)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.DataEmitterReader.onDataAvailable(DataEmitterReader.java:41)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.Util.emitAllData(Util.java:23)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:820)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:657)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
04-05 14:47:29.495 29873-7222/com.kartikgupta.protocreatar W/System.err:     at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:599)
`
Help me how to resolve it ...................I am sending a basic string only

**Comment by Kartik-RTP** [comment]
@nukix : Man tell me how you resolved the problem

**Comment by nukix** [comment]
@Kartik-RTP I resolved this error by use it as Module not `compile 'com.android.support:appcompat-v7:24.2.1'` last time. but i don't know whether it can run now.

**Comment by nukix** [comment]
@Kartik-RTP You can try it for yourself.

**Comment by Kartik-RTP** [comment]
Thanx for your information . I have managed to get it to work by simply
changing the version of library that i was using . So , I think I can do
with what I have at present. Thanks anyways.

Regards

Kartik Gupta
4th year , CSE Department
IIT Ropar

**Comment by Kartik-RTP** [comment]
For others 
I changed the gradle compile statement from 
`compile 'com.koushikdutta.async:androidasync:2.+'` as is mentioned in Readme of project
to 
`compile 'com.koushikdutta.async:androidasync:2.1.6'`
and its working for now

**Comment by nukix** [comment]
@Kartik-RTP Maybe the author had fixed this error.
