### ISSUE TITLE
WebSocket's setClosedCallback doesn't work

### ISSUE THREAD

**Issue by Godefroy** [koush/AndroidAsync#51]
First, I'd like to thank you for this amazing lib, it's impressive! I'm using it to develop a WebSocket and Socket.io plugin for Game Closure.

I tried to use setClosedCallback and setEndCallback to handle onclose event, but these callbacks seem to be never called.

```
AsyncHttpClient.getDefaultInstance().websocket(url, protocol, new WebSocketConnectCallback() {
    @Override
    public void onCompleted(Exception ex, WebSocket websocket) {
        // onopen

        websocket.setStringCallback(new StringCallback() {
            public void onStringAvailable(String data) {
                // onmessage
            }
        });

        websocket.setClosedCallback(new CompletedCallback() {
            public void onCompleted(Exception ex) {
                // onclose
            }
        });

        websocket.setEndCallback(new CompletedCallback() {
            public void onCompleted(Exception ex) {
                // ???
            }
        });
    }
});
```

I have some questions about that:
- Do I have a problem in my code or is there a bug?
- What is the endCallback supposed to do?
- During the closing operation, the websocket is supposed to continue to receive messages, but with this implementation, it seems to stop receiving messages just after the close statement. Is it a bug?
- Is it  possible to have the standard information that should be available with onclose event? (wasClean, code, reason)

**Comment by amallo** [comment]
Hi, I have same problem with setClosedCallback method 

- Callback is fired immediatly when closing my local server (CTRL + C)

- Callback is fired with a timeout when closing my remote HTTPS server. 

```java
AsyncHttpClient.getDefaultInstance().websocket(mHost, null, new AsyncHttpClient.WebSocketConnectCallback() {
                @Override
                public void onCompleted(Exception ex, WebSocket webSocket) {
                    if (ex == null){
                        
                        webSocket.setClosedCallback(new CompletedCallback() {
                            @Override
                            public void onCompleted(Exception ex) {
                                Log.d(TAG, "setClosedCallback wait for timeout with HTTPS server");
                            }
                        });
                    }
                    else{
                        Log.d(TAG, "ERROR "+ex.getLocalizedMessage());
                    }
                }
            });
```
It is a problem relative to SSL ?

Your lib is amazing, I use it to develop a collaborative application
