### ISSUE TITLE
JsonObject- JsonArray problem

### ISSUE THREAD

**Issue by doriwal** [koush/AndroidAsync#56]
in case i am sending json request 
the code in httpUtil : 

 if (JSONObjectBody.CONTENT_TYPE.equals(ct)) {
                    return new JSONObjectBody();
                }

does not check if its a json object or array so in case its array like [{ "a":"b"} ]
request.getBody() will return null as it will not parse the JSONArray

unless i will change the code like 

 if (JSONObjectBody.CONTENT_TYPE.equals(ct)) {
                    return new JSONArrayBody ();
                }

but now i wil get null value in case the request body is json object and not json array

**Comment by Jensen0618** [comment]
Thank you for the code, I just encountered this problem
