### ISSUE TITLE
multiDex error

### ISSUE THREAD

**Issue by nikitoSha** [koush/AndroidAsync#577]
Hello.
After updating gradle to 4.+ version, I can't make project because of this error:

> Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/koushikdutta/async/http/server/UnknownRequestBody;

What me do to run my app?
I use `multiDexEnabled true`. "false" not helped me :(

**Comment by nikitoSha** [comment]
Hey! :(

**Comment by ankitsaini84** [comment]
Hello! This seems to be a very late reply.. but following steps in this link seems to solve the problem.
https://developer.android.com/studio/build/multidex.html

Hope it helps. ^^

**Comment by nikitoSha** [comment]
@ankitsaini84 Hi! Yes, I already solve this problem and as I remember, this tutorial helps me. :))
Thank you:)
