### ISSUE TITLE
MultipartFormDataBody get File part

### ISSUE THREAD

**Issue by ldt116** [koush/AndroidAsync#64]
In https://github.com/koush/AndroidAsync/blob/master/AndroidAsync/src/com/koushikdutta/async/http/body/MultipartFormDataBody.java there's a method to addFilePart to the body but is there a way to get the File part out of the Body?

I'm writing a system involves multiple Android devices and I want to upload file from one device to another, is it possible for me to use this class for this purpose?

**Comment by offassets** [comment]
So, as @koush mentioned, using `setMultipartCallback` and the described method, is it possible to get parallel file uploads to the Async HTTP server?

Can you provide some information regarding how to get the file from POST upload.

Sorry, I'm new to this repo, but found it incredibly useful for my tiny projects, while using progress bar with submitting file upload, but stuck on file receiving part.

**Comment by koush** [comment]
a multipart body is not parallel. It uploads all the files as one blob, one at a time, which are then received by the server.

on AsyncHttpServer request callback, you can use request.getBody() and cast that to MultipartFormDataBody

**Comment by harshjv** [comment]
Many thanks for the quick reply. So, if I use AsyncHttpServer for my program, and from multiple devices, if I'm uploading file to it, simultaneously, it won't be possible to get and store all the files. Am I getting this correct?

And for that uploaded file, How do I get it back? I mean, after uploading it to server, how can I get the uploaded file? Is there something that can write it to a file?

Thanks

**Comment by offassets** [comment]
Many thanks for the quick reply. So, if I use AsyncHttpServer for my program, and from multiple devices, if I'm uploading file to it, simultaneously, it won't be possible to get and store all the files. Am I getting this correct?

And for that uploaded file, How do I get it back? I mean, after uploading it to server, how can I get the uploaded file? Is there something that can write it to a file?

Thanks

**Comment by swithun-liu** [comment]
> So I assume you're running HTTP servers on each android as well?
> 
> Posting multipart files is straightforward, but receiving them with AsyncHttpServer is a bit of a moving API.
> 
> Here's how it is done right now:
> 
> ```java
> mServer.post("/api/postfile", new HttpServerRequestCallback() {
>     FileOutputStream last = null;
>     @Override
>     public void onRequest(AsyncHttpServerRequest request, final AsyncHttpServerResponse response) {
>         final MultipartFormDataBody body = (MultipartFormDataBody)request.getBody();
>         body.setMultipartCallback(new MultipartCallback() {
>             @Override
>             public void onPart(Part part) {
>                 if (!part.isFile())
>                     return;
>                 try {
>                     if (last != null) {
>                         last.close();
>                         last = null;
>                     }
>                     body.setDataCallback(new OutputStreamDataCallback(last = new FileOutputStream(part.getFilename())));
>                 }
>                 catch (Exception ex) {
>                 }
>             }
>         });
>         request.setEndCallback(new CompletedCallback() {
>             @Override
>             public void onCompleted(Exception ex) {
>                 // all done!
>             }
>         });
>     }
> });
> ```


hi @koush , here `part.getFilename()` we get the filename, but how can i get the bytes of the file
