### ISSUE TITLE
Makes no sense!

### ISSUE THREAD

**Issue by librehome** [koush/AndroidAsync#685]
AsyncSSLSocketWrapper.java

Line 491:
                writeList.add(writeBuf);
                assert !writeList.hasRemaining();

The assertion will fail!
You just added a writeBuf, then you expect the remaining is 0?

**Comment by librehome** [comment]
I can confirm it is a bug!
I guess previous you guys shipped the package with assert stripped.
Now all of a sudden it is enable somehow.
Expect tons of SSL problems from now on!

**Comment by aantunovic** [comment]
since android gradle plugin 4.1 assertions are enabled by default in debuggable builds

maybe rebuilding this lib with proguard rule should solve this.
```
-assumenosideeffects class junit.framework.Assert {
*;
}
```

**Comment by vmalan** [comment]
yeah, this is biting me too.  please address!
FATAL EXCEPTION: ion-ion  
Process: [MYAPP], PID: 22067  
java.lang.AssertionError  
at com.koushikdutta.async.AsyncSSLSocketWrapper.write(AsyncSSLSocketWrapper.java:390)

**Comment by 2501272126** [comment]
help !!!
how can i avoid this bug?

**Comment by librehome** [comment]
Guys, it's simple!
1. Clone to repo to local
2. Delete that line or comment it out. I recommend deleting it.
3. Add the project to android studio. In build.gradle of app

implementation project(':AndroidAsync')

**Comment by koush** [comment]
Fixed in 3.1.0

**Comment by vmalan** [comment]
Thank you.  this library has been very useful and essential for many years.
